name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==1.8.2+cpu -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with Flake
      run: |
        flake8 --max-line-length=120 --exclude="test_*.py","build" .
    - name: Test with pytest
      run: |
        pytest . -vv
